[package]
name = "semantic-rs"
version = "0.1.0"
authors = ["Jan Schulte <hello@unexpected-co.de>", "Jan-Erik Rediger <janerik@fnordig.de>"]
description = "Automatic crate publishing"
license = "MIT"

[dependencies]
term = "0.2"
toml = "0.1"
regex = "0.1"
semver = "0.2.1"
docopt = "0.6.78"
rustc-serialize = "0.3.16"
git2 = "0.4.2"
clog = { git = "https://github.com/clog-tool/clog-lib.git" }
hubcaps = "0.2"
hyper = "0.7"
url = "0.5"
clippy = {version = "<0.1.0", optional = true}

[features]
default = []
dev = ["clippy"]
