version: 2

aliases:
  # -------------------------
  #      ALIASES: Caches
  # -------------------------
  - &restore-deps-cache-rust
    key: deps-cache-{{ arch }}-{{ checksum "Cargo.toml" }}

  - &save-deps-cache-rust
    key: deps-cache-{{ arch }}-{{ checksum "Cargo.toml" }}
    paths:
      - /usr/local/cargo/registry
      - ~/project/target/

  - &restore-deps-cache-musl
    key: deps-cache-musl-{{ arch }}-{{ checksum "Cargo.toml" }}

  - &save-deps-cache-musl
    key: deps-cache-musl-{{ arch }}-{{ checksum "Cargo.toml" }}
    paths:
      - ~/.rustup/
      - ~/.cargo/
      - ~/project/target/
  # -------------------------
  #  ALIASES: Branch Filters
  # -------------------------
  - &filter-only-master
    branches:
      only: master
  - &filter-only-semantic-pr
    branches:
      only:  /^(pull|fix|feat)\/.*$/

defaults: &defaults
  working_directory: ~/project
  environment:
    RUST_BACKTRACE: 1

jobs:
  build:
    <<: *defaults
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run: apt update && apt install -y cmake
      - restore_cache: *restore-deps-cache-rust
      - run: cargo build
      - save_cache: *save-deps-cache-rust

  test:
    <<: *defaults
    docker:
      - image: rust:latest
    steps:
      - checkout
      - restore_cache: *restore-deps-cache-rust
      - run: apt update && apt install -y cmake
      - run: rustup component add clippy
      - run: rustup component add rustfmt
      - run: cargo test --all
      - save_cache: *save-deps-cache-rust
      - run: cargo clippy
      - run: cargo fmt -- --check

  build-linux-release:
    <<: *defaults
    docker:
      - image: clux/muslrust
    steps:
      - checkout
      - restore_cache: *restore-deps-cache-musl
      - run: cargo build --release
      - save_cache: *save-deps-cache-musl
      - run: mv target/x86_64-unknown-linux-musl/release/semantic-rs ./semantic-rs-linux
      - persist_to_workspace:
          root: .
          paths:
            - semantic-rs-linux

  release-dry-run:
    <<: *defaults
    docker:
      - image: rust:latest
    steps:
      - checkout
      - attach_workspace:
          at: /workspace
      - run: /workspace/semantic-rs-linux

  release:
    <<: *defaults
    docker:
      - image: rust:latest
    steps:
      - checkout
      - attach_workspace:
          at: /workspace
      - restore_cache: *restore-deps-cache-rust
      # This unset is VERY important: without it --force-https cannot work
      # For some reason CircleCI has a global override substituting git@ links instead of all https links
      - run: git config --global --unset url.ssh://git@github.com.insteadof
      - run: /workspace/semantic-rs-linux
      - save_cache: *save-deps-cache-rust

workflows:
  version: 2
  analysis:
    jobs:
      - test:
          filters: *filter-only-semantic-pr
      - build-linux-release:
          filters: *filter-only-semantic-pr
      - release-dry-run:
          filters: *filter-only-semantic-pr
          requires:
            - test
            - build-linux-release

  release:
    jobs:
      - test:
          filters: *filter-only-master
      - build-linux-release:
          filters: *filter-only-master
      - release-dry-run:
          filters: *filter-only-master
          requires:
            - test
            - build-linux-release
      - hold:
          filters: *filter-only-master
          type: approval
          requires:
            - release-dry-run
      - release:
          filters: *filter-only-master
          requires:
            - hold
