version: 2

aliases:
  # -------------------------
  #      ALIASES: Caches
  # -------------------------
  - &restore-deps-cache
    key: deps-cache-{{ arch }}-{{ checksum "Cargo.toml" }}

  - &save-deps-cache
    key: deps-cache-{{ arch }}-{{ checksum "Cargo.toml" }}
    paths:
      - /usr/local/cargo/registry
      - ~/project/target/

  # -------------------------
  #  ALIASES: Branch Filters
  # -------------------------
  - &filter-only-master
    branches:
      only: master
  - &filter-only-semantic-pr
    branches:
      only:  /^(pull|fix|feat)\/.*$/

defaults: &defaults
  working_directory: ~/project
  environment:
    RUST_BACKTRACE: 1

jobs:
  build:
    <<: *defaults
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run: apt update && apt install -y cmake
      - restore_cache: *restore-deps-cache
      - run: cargo build
      - save_cache: *save-deps-cache

  test:
    <<: *defaults
    docker:
      - image: rust:latest
    steps:
      - checkout
      - restore_cache: *restore-deps-cache
      - run: apt update && apt install -y cmake
      - run: rustup component add clippy
      - run: rustup component add rustfmt
      - run: cargo test --all
      - save_cache: *save-deps-cache
      - run: cargo clippy
      - run: cargo fmt -- --check

  install:
    <<: *defaults
    docker:
      - image: ekidd/rust-musl-builder
    steps:
      - checkout
      - run: cargo build --release
      - persist_to_workspace:
          root: target/x86_64-unknown-linux-musl/release
          paths:
            - semantic-rs

  release-dry-run:
    <<: *defaults
    docker:
      - image: rust:latest
    steps:
      - checkout
      - attach_workspace:
          at: /workspace
      - run: /workspace/semantic-rs --write=no --release=no --branch=$CIRCLE_BRANCH --asset /workspace/semantic-rs --asset Changelog.md

  release:
    <<: *defaults
    docker:
      - image: rust:latest
    steps:
      - checkout
      - attach_workspace:
          at: /workspace
      - run: /workspace/semantic-rs --write=yes --release=yes --asset /workspace/semantic-rs --asset Changelog.md

workflows:
  version: 2
  analysis:
    jobs:
      - test:
          filters: *filter-only-semantic-pr
      - install:
          filters: *filter-only-semantic-pr
      - release-dry-run:
          filters: *filter-only-semantic-pr
          requires:
            - test
            - install

  release:
    jobs:
      - test:
          filters: *filter-only-master
      - install:
          filters: *filter-only-master
      - release-dry-run:
          filters: *filter-only-master
          requires:
            - test
            - install
      - hold:
          filters: *filter-only-master
          type: approval
          requires:
            - release-dry-run
      - release:
          filters: *filter-only-master
          requires:
            - hold
